-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 15:19:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Microdesafio1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Microdesafio1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Microdesafio1` DEFAULT CHARACTER SET utf8mb4 ;
USE `Microdesafio1` ;

-- -----------------------------------------------------
-- Table `Microdesafio1`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Categorias` (
  `id` INT NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Microdesafio1`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `contraseña` VARCHAR(45) NOT NULL,
  `Categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Categoria_id`),
  INDEX `fk_Usuarios_Categoria1_idx` (`Categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `Microdesafio1`.`Categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Microdesafio1`.`Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Cursos` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descipcion` VARCHAR(45) NOT NULL,
  `imagen` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_finalizacion` DATE NOT NULL,
  `cupo_max` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Microdesafio1`.`Unidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Unidades` (
  `id` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `Cursos_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Cursos_id`),
  INDEX `fk_Unidades_Cursos1_idx` (`Cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Unidades_Cursos1`
    FOREIGN KEY (`Cursos_id`)
    REFERENCES `Microdesafio1`.`Cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Microdesafio1`.`Usuarios_has_Cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Usuarios_has_Cursos` (
  `Usuarios_id` INT NOT NULL,
  `Cursos_id` INT NOT NULL,
  PRIMARY KEY (`Usuarios_id`, `Cursos_id`),
  INDEX `fk_Usuarios_has_Cursos_Cursos1_idx` (`Cursos_id` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Cursos_Usuarios1_idx` (`Usuarios_id` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Cursos_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `Microdesafio1`.`Usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Cursos_Cursos1`
    FOREIGN KEY (`Cursos_id`)
    REFERENCES `Microdesafio1`.`Cursos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Microdesafio1`.`Clases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Clases` (
  `idClases` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NOT NULL,
  `fecha_de_inicio` DATE NOT NULL,
  `visibilidad` INT NOT NULL,
  `Unidades_id` INT NOT NULL,
  `Unidades_Cursos_id` INT NOT NULL,
  PRIMARY KEY (`idClases`, `Unidades_id`, `Unidades_Cursos_id`),
  INDEX `fk_Clases_Unidades1_idx` (`Unidades_id` ASC, `Unidades_Cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Clases_Unidades1`
    FOREIGN KEY (`Unidades_id` , `Unidades_Cursos_id`)
    REFERENCES `Microdesafio1`.`Unidades` (`id` , `Cursos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Microdesafio1`.`Bloques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Microdesafio1`.`Bloques` (
  `idBloques` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `visibilidad` INT NOT NULL,
  `contenido` VARCHAR(45) NOT NULL,
  `Clases_idClases` INT NOT NULL,
  `Clases_Unidades_id` INT NOT NULL,
  `Clases_Unidades_Cursos_id` INT NOT NULL,
  PRIMARY KEY (`idBloques`, `Clases_idClases`, `Clases_Unidades_id`, `Clases_Unidades_Cursos_id`),
  INDEX `fk_Bloques_Clases1_idx` (`Clases_idClases` ASC, `Clases_Unidades_id` ASC, `Clases_Unidades_Cursos_id` ASC) VISIBLE,
  CONSTRAINT `fk_Bloques_Clases1`
    FOREIGN KEY (`Clases_idClases` , `Clases_Unidades_id` , `Clases_Unidades_Cursos_id`)
    REFERENCES `Microdesafio1`.`Clases` (`idClases` , `Unidades_id` , `Unidades_Cursos_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB; 


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
